### ISSUE TITLE
【DOC】トンマナ作成

### ISSUE THREAD

**Issue by kuruma-gs** [sikmi/sigotoconnect#7]
シゴトコネクトのイメージに合うトンマナを決める
各自、イメージの絵やサイトを持ってきてURLをコメントに貼ってください

**Comment by kuruma-gs** [comment]
マゼンダでこんなのとか
![ss 2015-04-13 18 08 26](https://cloud.githubusercontent.com/assets/65964/7112796/3b7fe11a-e208-11e4-9014-4fe6ca756711.png)
![ss 2015-04-13 18 08 34](https://cloud.githubusercontent.com/assets/65964/7112797/3e384f50-e208-11e4-93d2-0c4780aed0ee.png)
![ss 2015-04-13 18 09 03](https://cloud.githubusercontent.com/assets/65964/7112799/41207b2a-e208-11e4-85db-8e96e7227498.png)

**Comment by kuruma-gs** [comment]
こんな色でも良いかなとも
![ss 2015-04-13 18 11 29](https://cloud.githubusercontent.com/assets/65964/7112828/95c8b020-e208-11e4-9dd5-6cfa65969bb7.png)

**Comment by kuruma-gs** [comment]
こういのはおしゃれnオシャレなんですが、なかなか難易度が高いんですよねw
![ss 2015-04-13 18 26 32](https://cloud.githubusercontent.com/assets/65964/7113021/b4c08956-e20a-11e4-8658-a962bf116750.png)

**Comment by yuutabuchi** [comment]
![2015-04-13 18 27 45](https://cloud.githubusercontent.com/assets/7991269/7113037/dcb7861c-e20a-11e4-9353-ff09d3423d54.png)

**Comment by kuruma-gs** [comment]
ちょっとオシャレな感じ。
![ss 2015-04-13 18 28 21](https://cloud.githubusercontent.com/assets/65964/7113040/eab5726a-e20a-11e4-9190-9cb20f8cf264.png)

**Comment by yuutabuchi** [comment]
![2015-04-13 18 26 43](https://cloud.githubusercontent.com/assets/7991269/7113043/edaed2b8-e20a-11e4-889c-433dbd037092.png)

**Comment by yuutabuchi** [comment]
![2015-04-13 18 26 11](https://cloud.githubusercontent.com/assets/7991269/7113049/f977695c-e20a-11e4-919c-224fc59d63ce.png)

**Comment by yuutabuchi** [comment]
緑 と 赤で見てみた。

**Comment by kuruma-gs** [comment]
黄緑とかは女性にも人気か
![ss 2015-04-13 18 30 21](https://cloud.githubusercontent.com/assets/65964/7113075/2d671c62-e20b-11e4-8d0b-523195994bb7.png)

**Comment by kuruma-gs** [comment]
![ss 2015-04-13 18 31 31](https://cloud.githubusercontent.com/assets/65964/7113096/56a35f5a-e20b-11e4-8291-1d621448346e.png)

**Comment by kamomc** [comment]
アクセントカラーがいい感じ。
![2015-04-13 18 35 35](https://cloud.githubusercontent.com/assets/5961578/7113156/ed52669e-e20b-11e4-8587-b7216d2db1a6.png)


![2015-04-13 18 34 23](https://cloud.githubusercontent.com/assets/5961578/7113168/0499d454-e20c-11e4-9b80-17c82633ccfc.png)

**Comment by kuruma-gs** [comment]
https://www.airbnb.jp/
が綺麗なので参考にしたいです
